apiVersion: v1
kind: PersistentVolumeClaim
metadata:    
  finalizers:
  - kubernetes.io/pvc-protection      
  name: backup-arangodb-teste
  namespace: arangodb  
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-arangodb-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ssd  
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound